import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9],[10, 11, 12],[13, 14, 15]])
print("Shape of the array:", a.shape)
print("Size of the array:", a.size)
print("Number of dimensions:", a.ndim)
print("Data type of the array:", a.dtype)
print("Item size in bytes:", a.itemsize)
print("Total bytes consumed by the array:", a.nbytes)
print("Array Description:")
print(a)
array_type = a.astype(float)
print("Array with float data type:")
print(array_type)
print("Shape of the float array:", array_type.dtype)
